# Generated by Django 5.0.2 on 2025-05-02 10:06

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cuisine", models.CharField(blank=True, max_length=255, null=True)),
                ("title", models.CharField(max_length=255)),
                ("rating", models.FloatField(blank=True, null=True)),
                ("prep_time", models.IntegerField(blank=True, null=True)),
                ("cook_time", models.IntegerField(blank=True, null=True)),
                ("total_time", models.IntegerField(blank=True, null=True)),
                ("description", models.TextField()),
                ("nutrients", models.JSONField()),
                ("serves", models.CharField(max_length=100)),
            ],
        ),
    ]
